### PR TITLE
Added send queue for Telldus Core, created README

### PR DESCRIPTION
**Pull request by EliasGabrielsson**
- Made queue which only send the last relevant event to the radio interface.
- Started on a README, needs more work to be complete. Especially configuration examples.
- Wrote out Jarle Hjortland in ESH-INF so it will be displayed more nicely in the paper-ui.
- Changed "Tellstick Center" to "Tellstick Core" in bridge types.
  I found it messy with center because "Tellstick Live" API uses the "Tellstick Center" desktop app for configuration which confused me.

Signed-off-by: Elias Gabrielsson elias@rehash.se (github: EliasGabrielsson)

### CODE REVIEW

**Comment by EliasGabrielsson** [comment]
For your information:

I made the queue optimisation at API layer now. eg. Telldus Core have the queue not Telldus Live.
I think this is preferable because different API could have different need. Maybe Telldus Live already make this prioritization at server side.?

I also started working on a readme, according to guidelines this will be the preferred way until a doc generation could be made from the ESH data.

**Comment by EliasGabrielsson** [comment]
- [x] Add Thread.stop() when deactivating this binding.

**Comment by EliasGabrielsson** [comment]
@jarlebh 
Review comments from 1.x binding is applied to this PR as well.
Note the new dispose() function in TelldusDeviceController interface which originally delegated from openHAB. I made a http.close() call for the Telldus live service. Do that bridge need more cleanup?

**Comment by jarlehjortland** [comment]
Thank you @EliasGabrielsson, from the SmartHome guidelines it states that we should not create threads. https://www.eclipse.org/smarthome/documentation/development/guidelines.html

> _Creation of threads must be avoided. Instead, resort into using existing schedulers which use pre-configured thread pools. If there is no suitable scheduler available, start a discussion in the forum about it rather than creating a thread by yourself._

**Comment by EliasGabrielsson** [comment]
Got it, observant of you.
I will do a rewrite according to best practices. 
I can't give an ETA but will give it some time in the weekend. 
Need to read the documentation.

EDIT:
I will away this pull request to go into ESH before I rewrite these changesets.
https://github.com/eclipse/smarthome/pull/959

Depending on when things get merged I maybe do a PR directly to openhab2-addon, time will tell.

**Pull request merged**
